version: '3'

networks:
 test_network:

services:
  ############################### PHP
  php_test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: php_test
    volumes:
      - ./:/var/www/html/test
      - ./docker/xdebug/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    working_dir: /var/www/html/test
    networks:
      - test_network
  ############################### NGINX
  nginx_test:
    image: nginx:latest
    container_name: nginx_test
    ports:
      - "8066:80"
    volumes:
      - ./:/var/www/html/test
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test_network

  ############################### DB
  pgsql_test:
    build:
      context: ./docker/db_conf
      dockerfile: Dockerfile
    container_name: pgsql_test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    restart: unless-stopped
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    tty: true
    networks:
      - test_network
    expose:
      - 5432
  ######################## COMPOSER #########

  composer_test:
    image: composer
    container_name: composer_test
    volumes:
      - ./:/var/www/html/test
      - ./docker/composer_cache:/root/.composer/cache
    working_dir: /var/www/html/test
    depends_on:
      - php_test
    networks:
      - test_network

# run this command to create network in docker `docker network create test_network`
#  elasticsearch_test:
#    image: 'elasticsearch'
#    container_name: elasticsearch_test
#    ports:
#      - "9200:9200"
#    environment:
#      - "discovery.type=single-node"
#      - "xpack.security.enabled=false"
#    networks:
#          - test_network
#    expose:
#      - 9200
